# This file was updated with the Mesa Configuration Tool on Jun 13 2026 18:16:04
# Changes to most things are ok and will be read by the Configuration Tool

[MESA]
VERSION = 2.1.8
BOARD = 7i97
BOARD_NAME = 7i97t
FIRMWARE = Select
CARD_0 = None
CARD_1 = None

[EMC]
VERSION = 1.1
MACHINE = burny_7i97t_test
DEBUG = 0x00000000

[HM2]
DRIVER = hm2_eth
ADDRESS = 10.10.10.10

[DISPLAY]
DISPLAY = axis
PROGRAM_PREFIX = /home/web/linuxcnc/nc_files
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = ACTUAL
MAX_FEED_OVERRIDE = 1.2
MIN_LINEAR_VELOCITY = 5.0
DEFAULT_LINEAR_VELOCITY = 1.0
MAX_LINEAR_VELOCITY = 5.0
MIN_ANGULAR_VELOCITY = 0.0
DEFAULT_ANGULAR_VELOCITY = 0.0
MAX_ANGULAR_VELOCITY = 0.0
CYCLE_TIME = 0.1
INTRO_GRAPHIC = emc2.gif
INTRO_TIME = 0
OPEN_FILE = ""

[KINS]
KINEMATICS = trivkins coordinates=X
JOINTS = 1

[EMCIO]
EMCIO = iov2
CYCLE_TIME = 0.100
TOOL_TABLE = tool.tbl

[RS274NGC]
PARAMETER_FILE = parameters.var
SUBROUTINE_PATH = /home/web/linuxcnc/subroutines

[EMCMOT]
EMCMOT = motmod
COMM_TIMEOUT = 1.0
SERVO_PERIOD = 1000000

[TASK]
TASK = milltask
CYCLE_TIME = 0.010

[TRAJ]
COORDINATES = X
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
MAX_LINEAR_VELOCITY = 0.0
NO_FORCE_HOMING = 1

[HAL]
HALFILE = main.hal
HALFILE = io.hal

[AXIS_X]
MIN_LIMIT = -100
MAX_LIMIT = 100
MAX_VELOCITY = 5
MAX_ACCELERATION = 20

[JOINT_0]
CARD = 0
TAB = 0
AXIS = X
MIN_LIMIT = -100
MAX_LIMIT = 100
MAX_VELOCITY = 5
MAX_ACCELERATION = 20
TYPE = LINEAR
SCALE = 1000
ANALOG_SCALE_MAX = 10
ANALOG_MIN_LIMIT = -10
ANALOG_MAX_LIMIT = 10
ENCODER_SCALE = 1000
FERROR = 5
MIN_FERROR = 1
DEADBAND = 0
P = 1
I = 0
D = 0
FF0 = 0
FF1 = 0
FF2 = 0
BIAS = 0
MAX_OUTPUT = 1
MAX_ERROR = 0
HOME = 0
HOME_OFFSET = 0
HOME_SEARCH_VEL = 0
HOME_LATCH_VEL = 0
HOME_FINAL_VEL = 0
HOME_SEQUENCE = 0

[INPUTS]
# DO NOT change the inputs they are used by the configuration tool
INPUT_0_0 = Joint 0 Minus Home
INPUT_INVERT_0_0 = True
INPUT_SLOW_0_0 = False
INPUT_0_1 = Joint 0 Plus
INPUT_INVERT_0_1 = True
INPUT_SLOW_0_1 = False

[OUTPUTS]
# DO NOT change the outputs they are used by the configuration tool

[OPTIONS]
# DO NOT change the options they are used by the configuration tool
LOAD_CONFIG = False
INTRO_GRAPHIC = emc2.gif
INTRO_GRAPHIC_TIME = 0
MANUAL_TOOL_CHANGE = False
CUSTOM_HAL = False
POST_GUI_HAL = False
SHUTDOWN_HAL = False
HALUI = False
PYVCP = False
GLADEVCP = False
LADDER = False
BACKUP = False
